### ISSUE TITLE
Request state page

### ISSUE THREAD

**Issue by themetalone** [GSE-Project/SS2016-group2#102]
We're still missing a page where the user sees the state of his/her requests

### Update 28.06.2016

- [ ] A more intuitive way of representing the state of an request (with colors or so)
  - Rejected - red
  - Pending - yellow
  - Accepted - green
- [x] Using more information (currently the server sends way more information than we use)
- [x] Allow the user to cancel pending tasks (state 6 on the server)
- [x] Actually refresh the states

**Comment by skaldo** [comment]
Was this part of the requirements for this iteration?

If you are working on this (it's active), please add it instead of the "where is my bus" button on the home screen. If not, I can take care of it now.

**Comment by themetalone** [comment]
Did i make it active? Sry my Bad.
I thought it to be since how should the User know that He/she will be
picked up

Dominik Skalník <notifications@github.com> schrieb am Mo., 27. Juni 2016,
13:32:

**Comment by skaldo** [comment]
Now we have a basic request state page. We cannot do more until the server provides us more information.
I'm postponing this to the next iteration.

**Comment by themetalone** [comment]
Development on branch 102_request_page

**Comment by themetalone** [comment]
I found that the current structure in the data logic is insufficent. I'll perform some major changes for the request states

**Comment by themetalone** [comment]
I implemented the requestChange into the datalogic. This is ready to integrate into the UI. 

The request page updates upon pulling down. This works with the current G1 Server

**Comment by themetalone** [comment]
I'm done with my additions

**Comment by skaldo** [comment]
I'm going to do the colors later today.
