### ISSUE TITLE
Increase Coverage

### ISSUE THREAD

**Issue by themetalone** [GSE-Project/SS2016-group2#106]
During the last 2 Iterations our code coverage droped from awesome 90% to awefull 70% due to a lot of code additions. 

Maybe we should try to make the coverage at least yellow again

**Comment by tim284** [comment]
I will trd to do this. Maybe @themetalone can help me if i get some troubles?

**Comment by themetalone** [comment]
That's what I'm here for

tim284 <notifications@github.com> schrieb am Mi., 29. Juni 2016, 15:33:

**Comment by skaldo** [comment]
@tim284 do you have anything, or should we cancel this one?

**Comment by skaldo** [comment]
In order to focus us for the final presentation and to have more time for the more important tasks, I'm cancelling this issue!
