### ISSUE TITLE
Align the time zones

### ISSUE THREAD

**Issue by themetalone** [GSE-Project/SS2016-group2#107]
During the testate for Iteration 3 we encountered a problem with the time representation across the 3 Groups

### Problem

Currently we use UTC+0 for representation while @GSE-Project/group3 uses UTC+2. This leads to the problem that the citizen means one time while the bus driver means another, but both use the same unix timestamp. 

### TODO

Change our representation to UTC+2 since this is the timezone the application will work in.

**Comment by themetalone** [comment]
The problem seems to be located in the request page. The time is displayed correctly in the request state page

**Comment by skaldo** [comment]
I'm unable to test my fix due to the https://github.com/GSE-Project/SS2016-group1/issues/96.
I'll continue as soon as they fix it.
