### ISSUE TITLE
Update Traceability matrix

### ISSUE THREAD

**Issue by ricarda42** [GSE-Project/SS2016-group2#110]
As discussed in the Requirements Engineering meeting and mentioned in an e-mail from me some weeks ago, I still need an updated Traceability matrix from you. Anne said she wanted a common traceability matrix from all groups and I'd volunteer to put it together, but I need an up-to-date traceability matrix from you for that.

**Comment by skaldo** [comment]
@mmueller301, you were assigned to the initial traceability issue (https://github.com/GSE-Project/SS2016-group2/issues/17). If I'm mistaken, please assign the correct person, that did the traceability before.

Could you please handle this one as well?

Please pass the output to @ricarda42.

**Comment by mmueller301** [comment]
@ricarda42 sent you the document via mail
