### ISSUE TITLE
Develop a mock server for the API

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group2#16]
As we don't have any API against to test, a mock server has to be developed.
The server should take the data from the /Iteration_X/RestApi/TestData. The Iteration should be configurable at the startup of the server.

- [x] Develop it. @skaldo
- [x] Write howto into wiki. @skaldo
Wiki paragraph is available here: https://github.com/GSE-Project/SS2016-group2/wiki/Developer-documentation#how-to-use-it

**Comment by patrickmuessig** [comment]
i think there is /busses/:id missing

**Comment by skaldo** [comment]
The server development is done. Any improvements are going to be assigned to this issue.
