### ISSUE TITLE
Enable Traceability

### ISSUE THREAD

**Issue by ChristianAGSE** [GSE-Project/SS2016-group2#17]
The to-be scenarios in the requirements document should be traceable to your system functions.

So you might add a row in the table of the to-be-scenario:
Refined in system functions: SF_C1, SF_C3

In the SF function table you should have two row like:
Used in To-be-Scenarios: TBS_1, TBS_4
Implemented in Components: Gui, BusPosition

**Comment by ChristianAGSE** [comment]
This task should be done by group 2; So the assignment of @mbaniasad was a mistake.

**Comment by skaldo** [comment]
@mmueller301, @A0b10, any news regarding this issue? If you're stuck somewhere, try asking @tim284 and @patrickmuessig for help. This issue needs to be closed as soon as possible.
Thanks!

[Here](https://github.com/GSE-Project/SS2016-group3/blob/master/Requirements/tracebility%20matrix.doc)'s an example of what the G3 has done so far.

**Comment by skaldo** [comment]
Hi all, is this done? Please close it.

**Comment by ChristianAGSE** [comment]
@mmueller301 some content should be added. So the issue remains opened.

**Comment by ChristianAGSE** [comment]
Open TODOs:

- [ ] add author to traceability matrix
- [ ] add reviewer to traceability matrix
- [ ] trace system functions to architecture
