### ISSUE TITLE
Add more functionality to the map component

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group2#21]
Add some methods to
- [x] add a marker to the map - make it customisable (e.g. color, icon,...)
- [x] remove a marker
- [x] move the marker

- [x] think of other possible functions
- [x] Document the component (add a UML Class diagram to the document and describe the functionality briefly) I think here can @A0b10 help you.

Map component should be aware of the currently displayed markers, so that we can add e.g. some animations if the marker moves,..

#9

**Comment by skaldo** [comment]
Any news about the docs generation? Please adjust the comments in the component as described here: http://typedoc.io/guides/doccomments.html#function-signatures.
For the `deleteMarker` function it is sufficient to do following:
```javascript
  /**
   * Removes the marker based on the name.
   * @param markername Marker to be deleted
   */
  deleteMarker(markername) {
    this.markers[markername].setMap(null);
  }
```

Thanks!

**Comment by mmueller301** [comment]
I don't know why at the moment, but actually the generation tool does not work for me. I annoteted the comments, maybe you can just run the typedoc generator @skaldo

**Comment by skaldo** [comment]
Hi all, I think, that this issue is resolved already. Please check it @mmueller301 and @A0b10 and close it if no other work is needed.
