### ISSUE TITLE
Travis build for unit tests does not fail

### ISSUE THREAD

**Issue by may-bee** [GSE-Project/SS2016-group2#22]
Possibly, you already have seen, that currently the unit-test build is running and although no test are running, you do not get any failing build. Might be worth to have a look at it to gain consistent build results :)

```
SUMMARY:
✔ 0 tests completed
```

**Comment by skaldo** [comment]
Thank you for the issue.
The required change is prepared. As we are facing some difficulties in our data layer and need to do some rework, I'll push it once we make sure, that the tests do match the new internal structure.
