### ISSUE TITLE
PersistentDataProvider: Allow Timestamps to be stored

### ISSUE THREAD

**Issue by themetalone** [GSE-Project/SS2016-group2#29]
At the moment the PDP is initialized with a timestamp where each entry is set to -2. This would be fine but there is no access to the storage to fetch the last stored timestamp. There isn't even a `putTimeStamp` method. 

- [ ] Add `putTimestamp(data: UpdateData):void` to PDP
- [ ] Rework the `getTimestamps(): UpdateData` in PDP
- [ ] Integrate into CitizenDataService **without** changing the interfaces

**Comment by skaldo** [comment]
- `putTimestamp` is not needed as we update the timestamps each time we save an IXY object.
- `getTimeStamps()` is ok.
- The problem is, that we do not fetch the previous state from the LocalStorage.

I'm not sure about the testing, there you'll need to either mock the Storage instance or fake the data in the LocalStorage directly.

**Comment by themetalone** [comment]
A proposal: We add  
`isReady():Observable<boolean>{ }`method to the PDP that states true if the PDP is initilialized. This way we simply check at the CDS if the PDP is done before we attempt the access.

**Comment by skaldo** [comment]
That would be a possibility, but I think that we could solve it more elegantly.
Almost all the methods of our class return the observables. So what we could do is that at the beginning of each call we would first check the state. If there would be an update needed, we'd do that and afterwards we'd first call the the initially called method and resolve the observable afterwards.
I don't think that we do need to rush with this issue. Let's keep the discussion going, I'm pretty sure that we'll find a proper solution!

**Comment by themetalone** [comment]
And of course I already implemented that into the PersistentDataProvider XD But for now my changes haven't caused a test to fail
