### ISSUE TITLE
System Tests Iteration 1

### ISSUE THREAD

**Issue by themetalone** [GSE-Project/SS2016-group2#34]
Perform the system tests with respect to the [wiki](https://github.com/GSE-Project/SS2016-group2/wiki/System-Test-Cases). 

Document the tests with platform specs, date, time, execution details, expectations and errors in a new wiki page. 

Errors should be reported as bugs here asap! (Since we want to be prepared for tomorrow's attestation)

Assigned: @patrickmuessig and @tim284 

Related to this one: #45

**Comment by themetalone** [comment]
Have a look at https://github.com/GSE-Project/SS2016-group3/wiki/Sytem-Test-Cases

**Comment by skaldo** [comment]
This issue should be closed asap in order to have complete release documentation.
