### ISSUE TITLE
Communicate and finalize interface specification

### ISSUE THREAD

**Issue by maybeec** [GSE-Project/SS2016-group2#37]
You should finalize and communicate the interface specification with the other groups to be able to integrate in iteration 2.

GSE-Project/SS2016-group1#35
GSE-Project/SS2016-group3#23

**Comment by skaldo** [comment]
[Here](https://github.com/GSE-Project/SS2016-group2/wiki/Interface-meeting-outputs#22052016) is the summary of today's meeting (G1 - G2).
