### ISSUE TITLE
Create a config service

### ISSUE THREAD

**Issue by themetalone** [GSE-Project/SS2016-group2#41]
At the moment a lot of data is hard coded into your application. We should create a configuration file and an injectable service to read those data.

**Comment by themetalone** [comment]
# Concept
The current aproach uses Angular2 rc1 Routing with the OnActivate Interface 
## Changes 
HomePage now implements angular2/router/OnActivate 
App.ts has now an @Routes decorator that routes '/' to HomePage 
## How it works 
On App start HomePage is instantiated and routerOnActivate is called. If routerOnActivate returns a promise (which it does) the App waits until the promise is resolved. RouterOnActivate therefore Calls ConfigurationService.load() that is resolved when the config is loaded

**Comment by themetalone** [comment]
Nothing worked here so we fell back to the 'Holzhammer' approach:
# The Holzhammer approach
## The Config File
The config file is now a JavaScript (Typescript) file defining a config object. 
## Concept
The ConfigService loads the configuration from the new config.js file and provides it to all asking classes. No Interface was changed

**Comment by skaldo** [comment]
# yay! :hammer::hammer::hammer::hammer::hammer:
