### ISSUE TITLE
App fails if there's no data in the LocalStorage

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group2#43]
I have found a bug in our CDS. There are no null pointer checks.

- [x] Fix it!
- [ ] As this has been found by coincidence only, add a test case to address this. @themetalone

**Comment by themetalone** [comment]
Moving from [First Release](https://github.com/GSE-Project/SS2016-group2/milestones/First%20Release) to [Iteration 2](https://github.com/GSE-Project/SS2016-group2/milestones/Iteration2) since Testing isn't relevant for the first release
