### ISSUE TITLE
Android/iOS builds

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group2#45]
As discussed after the meeting, please try to build the application for Android and perform the system test:

- [x] @patrickmuessig: Android
- [x] @mmueller301: iOS

If you encounter any problems on the device, please open new bug issues. If you face any troubles during the build process, describe these here as comments.

**Please note, this issue has high priority, so that we can fix the possible issues before the release.**

**Comment by themetalone** [comment]
# Internet Access of the Application
[Cordova Whitelist plugin](http://docs.ionic.io/docs/cordova-whitelist)

`ionic plugin add https://github.com/apache/cordova-plugin-whitelist.git`

**Comment by patrickmuessig** [comment]
Yeah build an unsigned apk sucessfully, but was not able to test it for now.

**Comment by skaldo** [comment]
@mmueller301 & @tim284, I'd need the build artifacts (.ipa & .apk files) from you.
I'll add these to the release.

Thanks!
Dominik

**Comment by themetalone** [comment]
Should be closed with the milestone after publishing the releases

**Comment by themetalone** [comment]
Closed with @skaldo s release
