### ISSUE TITLE
UML diagram

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group2#46]
It would be great to have a overview diagram containing all our classes and their interactions.

Diagram should contain:
- [ ] CDS PDP RDP
- [ ] Models
- [ ] UI (BusDetailPage, StopsPage,...) *here include just the most critical ones*

**See this as an example:**
https://github.com/GSE-Project/SS2016-group3/blob/master/Doc/Architecture/Architecture%20-%20Component%20Diagram.pdf
https://github.com/GSE-Project/SS2016-group3/blob/master/Doc/Architecture/
**Here is a raw PowerPoint overview:**
[overall_architecture_overview_v3.pdf](https://github.com/GSE-Project/SS2016-group2/files/275278/overall_architecture_overview_v3.pdf)

@A0b10 feel free to request help from the developers of the components. If it is too much work, we can split this between other team members.

**Comment by ChristianAGSE** [comment]
Are the components so complex, that you really require it?

You can make additional diagrams, but from my point of view it is not necessary.

**Comment by skaldo** [comment]
From my point of view, we don't need it as we can live with the generated documentation. I thought that such a kind of documentation should be part of the project's outcome.
