### ISSUE TITLE
The map component does not work on iOS

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group2#49]
Found during #45 
<img width="250" alt="bildschirmfoto 2016-05-21 um 15 18 11" src="https://cloud.githubusercontent.com/assets/396663/15453682/50a60c30-201f-11e6-80e1-2328db2a1443.png">

**Comment by skaldo** [comment]
This seems to be related to #44. Please, fix the #44 first and then we'll check if the problem persists on the iOS..

**Comment by themetalone** [comment]
Neither on Android (Sony Xperia Z3C)
![screenshot_20160523-122705](https://cloud.githubusercontent.com/assets/8233984/15468066/4c5cc68c-20e2-11e6-8d4b-8c9f32b57fa9.png)
