### ISSUE TITLE
REST API Specification and documentation

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group2#5]
- [x] Prepare 1st draft of the REST API specification | Participated: @GSE-Project/group2
- [x] Discuss the draft with the Group 1 | Responsible: @mmueller301, @themetalone 
- [x] Create a version for review | Responsible: @themetalone 
- [x] Review | Responsible: @skaldo
- [x] Create Apiary documentation | Responsible: @patrickmuessig, @tim284

Part of the: #3

**Comment by tim284** [comment]
#5 done
