### ISSUE TITLE
Bug Detail Page seems to be broken on Android

### ISSUE THREAD

**Issue by themetalone** [GSE-Project/SS2016-group2#51]
Used Device: Sony Xperia Z3C with Android 6.0.1

<img width="250" alt="screenshot_20160523-122801" src="https://cloud.githubusercontent.com/assets/8233984/15468206/30dd3832-20e3-11e6-898c-9c750e68216a.png"> <img width="250" alt="screenshot_20160523-122807" src="https://cloud.githubusercontent.com/assets/8233984/15468207/30e31752-20e3-11e6-849f-9c649a8aa1e6.png">

The Stops-List is rendered as aspected but on accessing the Bus-Detail Page only a blank page is displayed. The Map on the Position tab is also missing

**Comment by themetalone** [comment]
Well at least the map seems to work sometimes

**Comment by skaldo** [comment]
@themetalone Can you provide some more informations? Does the app try to get the bus information from the server? Are there any errors in the console?

**Comment by themetalone** [comment]
Not reproducable in current build (travis build number 166). Bus detail page renders as expected
