### ISSUE TITLE
Add the logging service

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group2#53]
As we've upgraded the AngularJS to the RC1, the logger proposed by @themetalone might be used.

- [x] Define what we expect from the logging service
- [x] Try to use the logging service @themetalone found

**Comment by themetalone** [comment]
## State of the work: 
I tried angular2-logger and jsnlog as possible canditates for our logger framework **BUT**

-  angular2-logger produces the really informative 
```
CitizenApplication\node_modules\angular2-logger\core.ts:1
import {provide} from "@angular/core";
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module' 
```
- jsnlog cannot be found when imported (for whatever reason)

## Conclusion
I'll write us an own logger service fitting our needs (and actually working without problems). This will be much faster than fixing any of the two problems above

**Comment by themetalone** [comment]
# What do we want from a Logger Service?
## Necessary
- Debug / Info / Warning / Error log-levels
- configurable displayed log level 
- 
## Nice to have
- colored output

**Comment by themetalone** [comment]
# Documentation

https://github.com/GSE-Project/SS2016-group2/wiki/The-Logger-Service
