### ISSUE TITLE
Switch to the native GoogleMaps

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group2#54]
Due to the fact that the application is going to be used in areas with weak cellular reception, we'll have to use the native maps.

Develop equivalent of the map component with following methods:
- [x] createMap
- [x] addMarker
- [x] moveMarker
- [x] removeMarker

It would be also great to have an interface specified, so that we could swap the native map component with the javascript one. Anyway, we'd need to discuss this point, as it might be just waste of time for our purpose.

@mmueller301 and @skaldo are going to work on this one.

**Comment by skaldo** [comment]
@mmueller301 Any progress on this one?
It would be great to see it in action tomorrow. If it wouldn't be for some reason possible to prepare a demo, be prepared to describe the troubles so that we could quickly solve these.

Thanks!

**Comment by skaldo** [comment]
@mmueller301: I got the native google maps running in the Ionic environment. You can start working on the other features.
@ttmher: You could help us with testing this on Android & helping Marcel with the other features.

Please note, that there are several hacks applied in order to make this work. I'm going to get rid of these during the weekend. You don't have to worry about your work, my changes are not going to affect the functionality you implement.

**Comment by ttmher** [comment]
@skaldo thanks for your help. 
I tested it on Android and its working. I will give my best and help Marcel with the other functions.
![screenshot_2016-06-09-23-29-52](https://cloud.githubusercontent.com/assets/18562771/15947138/51c54f7a-2e9a-11e6-9cc8-2e996fa0a85f.png)

**Comment by skaldo** [comment]
@mmueller301 any news? Or there's still the problem on the bus-detail page?
It would be good if you could summarize here what needs to be done, so that we can make sure that everything is going to work at the customer demo.

**Comment by mmueller301** [comment]
@skaldo yes currently trying to figure out where the bugs come from. Need help
<img width="315" alt="bildschirmfoto 2016-06-19 um 15 34 12" src="https://cloud.githubusercontent.com/assets/18538843/16177621/7e3696d6-3633-11e6-9b15-27dd11005977.png">
<img width="307" alt="bildschirmfoto 2016-06-19 um 15 34 20" src="https://cloud.githubusercontent.com/assets/18538843/16177622/89067342-3633-11e6-9604-d5a1a60478b4.png">

**Comment by mmueller301** [comment]
@ttmher now I have the same problem as you. The map shows only up when I reload it, did you fix this in your app?

**Comment by ttmher** [comment]
@mmueller301 unfortunately i still didn't found a solution

**Comment by skaldo** [comment]
@mmueller301 sorry, I was the whole day busy with the #63 and could not multitask somehow. I assume there has been no progress. I'll check that one as soon as I'll be free. Hopefully tomorrow.

As I understand it, we do not only have problems on the bus detail screen, but on the navigator too?

@ttmher and do you have any workaround? Or is the native map component not supported in your app at all?

**Comment by ttmher** [comment]
@skaldo i tried some ideas i had, but they all failed, at the moment im trying to implement all needed functions, so that i can use them when this problem is fixed. Actually i want to have a working native map for the next testate.

**Comment by skaldo** [comment]
@mmueller301 The bugs are solved. See #92.

Please start working on implementation of the functionality of the javascript GoogleMap component. See the request stop branch, here I've done some enhancements that I need for the request stop functionality.
