### ISSUE TITLE
Clean up the imports

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group2#56]
We can put some of the imports on one line only. Please check all .spec.ts files and wherever possible, import the classes on one line.

E.g.: https://github.com/GSE-Project/SS2016-group2/blob/feature/logger/CitizenApplication/app/specs/providers/data/CitizenDataService.spec.ts#L1-L20

**Comment by themetalone** [comment]
Removed 'effort (low)' label since this issue proved to be the equivalent of pandoras box
