### ISSUE TITLE
Complete Bus Detail Page

### ISSUE THREAD

**Issue by themetalone** [GSE-Project/SS2016-group2#57]
## Current State
The Bis Detail Page only shows a picture and the map. 

## Task
Add the missing information according to the requirements documentation

**Comment by skaldo** [comment]
#### IC_C2 specifies following:

- Estimated arrival of the bus
- Bus line number / color
- Map with the position of the bus (fixed, without zoom or pan option)

I'll take care of this one. :running:

**Comment by themetalone** [comment]
Following the system test document the bus detail should also show the number of free seats

**Comment by skaldo** [comment]
The number of seats is not implemented on the server yet. Should we close this until they implement it? Please denote this fact in the system test document.

**Comment by themetalone** [comment]
Good point. Maybe we could insert a dummy but I would not like to produce more work tonight than necessary

**Comment by skaldo** [comment]
Good. I would just leave it like it is, if we state clearly that this is not supported in the iteration 2 release, it should be fine. It also not present in the [interface specification](https://github.com/GSE-Project/SS2016-group1/wiki/Server-interfaces), though. We should talk to Mohammad tomorrow.

**Comment by skaldo** [comment]
@tim284 is currently working on this issue via #85.

**Comment by skaldo** [comment]
Done via #85.
