### ISSUE TITLE
Make our application API compliant

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group2#66]
Due to the fact, that we were using the mock server and had no access to the one from G1, we do use old APIs. In order to make us compliant with the specification, we have to do following:

 - [x] **Lines**: routeRef => routeId
 - [x] **Routes**: change the GPS, see: http://gsepg1.skaldo.cz/services/rest/linemanagement/v1/routes <=> http://gsep.skaldo.cz/routes
 - [x] **Schedules**: time <=> arrivingTime
 - [x] **Bus**: change the position http://gsepg1.skaldo.cz/services/rest/linemanagement/v1/busses/1 <=> http://gsep.skaldo.cz/busses/1

- [x] We have to change the addresses of the API endpoints in the config file to match the API paths as well.

After closing this one we can close #38.

**Comment by themetalone** [comment]
Created 2 independent branches to fix this

- One uses an mapper which allows us to use our current data model
- The other adapted the current server api 

Both branches resolve this issue. Chose one

**Comment by skaldo** [comment]
Good job @themetalone,
as the interface should not change that much from now, and as it is possible to talk to G1, I'd take the 2nd solution. It does not add additional complexity to our application and we are not going to need to maintain additional service.
I also reviewed the 2nd solution right now.

Thanks!
