### ISSUE TITLE
2nd release

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group2#68]
After finishing the #38, #57 and #66 we should release an API compliant release of our application.

To release the the application following needs to be done:

- [x] Merge #66 | @themetalone 
- [x] Complete the bus detail page #57 | @skaldo
- [x] Perform the system test (as we are going to test the app with the G1's API, we can call this integration test) | @tim284 (Android & Web), @patrickmuessig (Android & Web), @mmueller301 (iOS)
- [x] Do the release | @skaldo

_If the #52 is going to be done, we can squeeze it into the release too. | @A0b10_

**Comment by themetalone** [comment]
For the release packages we should set the `misc.log_level` configuration attribute to `info`

**Comment by skaldo** [comment]
@mmueller301 did not manage to perform the system test.
As this is not that critical, I'm closing this one.
