### ISSUE TITLE
Documentation of the requirements in the mConcAppt document.

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group2#7]
Parts of the documents (Only the persons of the parts that are related to the CitizenApp are mentioned here)
- [x] Stakeholders and Goals | Author: @mmueller301 | Reviewer: @skaldo  
- [x] Personas | Author: @themetalone | Reviewer: (@mmueller301)
- [x] As-Is Situation | Author: @skaldo | Reviewer: (@mmueller301)
- [x] System Functions | Author: @skaldo, @themetalone  | Reviewer: @mmueller301 
- [x] Interaction Cases | Author: @skaldo, @mmueller301 
- [x] Screen flow | Author: @skaldo | Reviewer: @GSE-Project/group2 
- [x] Mockups | Author: @skaldo | Reviewer: @GSE-Project/group2 

Part of the #3

**Comment by themetalone** [comment]
Closed since all subissues are resolved
