### ISSUE TITLE
Cannot Access Data on test server

### ISSUE THREAD

**Issue by themetalone** [GSE-Project/SS2016-group2#70]
When I try to access the server at gsepg1.skaldo.cz I encounter

`XMLHttpRequest cannot load http://gsepg1.skaldo.cz/services/rest/linemanagement/v1/stops. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access.`

 ## Tasks

- [ ] try to reproduce the bug
- [ ] If reproducable: try to fix it (this seems to be a problem on the server then)

**Comment by skaldo** [comment]
Hi Steffen,
thanks for this bug. I haven't explicitly enabled CORS on my server. I've added the appropriate headers to each request now:

```
Access-Control-Allow-Methods:GET, POST, OPTIONS
Access-Control-Allow-Origin:*
```

I can't test it right now, please let me know it it works.

**Comment by themetalone** [comment]
Closed
