### ISSUE TITLE
Implement the filtering of the stops

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group2#73]
It would be great if we could make the search field on the stop list page working.

The event handlers of the search field of the controller are already present, we need to implement the filtering only.

Do the #74 first.

**Comment by tim284** [comment]
I would try to implement it. Is it really only the filtering, e. g i type "a"  and it shows all stops starting with "a"?

**Comment by themetalone** [comment]
For the start I would implement just that, although case insensitive

**Comment by tim284** [comment]
All right

**Comment by skaldo** [comment]
Please, wait with this one. We should define a way how are we going to deal with UI related logic,so that we do not end up with spaghetti code.
Let's discuss it after spsm in person.

Please note that the release and system test do have higher priority now, as we have to be done until tomorrow.

**Comment by themetalone** [comment]
Solved in #74
