### ISSUE TITLE
Map doesn't show Bus

### ISSUE THREAD

**Issue by themetalone** [GSE-Project/SS2016-group2#77]
The map on the Bus-Detail page only shows the cititzen marker but should also contain the bus marker  (somewhere)

**Comment by skaldo** [comment]
I've added the functionality to the controller. Seems to be problem of the map component. Please @mmueller301 have a look.
#### Reproduction:
You can reproduce it by setting a brakpoint on the line 45 of the `bus-detail.ts` file.

**Comment by skaldo** [comment]
As the 2nd version has been released, I'm postponing this one to the 3rd iteration.

**Comment by skaldo** [comment]
@themetalone please check if this is still relevant, as we are only using the native maps.
Thanks!
