### ISSUE TITLE
The CDS always requests the data from the API

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group2#91]
- [x] The problem is that there's no timer implemented for update of the timestaps.
- [x] The Model is wrong, IRestObject should have timeStamp property, not timestamp.
- [x] The condition `serverTime < data.timeStamp` should contain is equal to.

All these issues are fixed on my pc, I'll push these to the GitHub as soon as I finish the #63.

It would be great if somebody could write tests for this. So that it does not happen anymore.
- [x] If the data in the LocalStorage is the same as the one on the server and the CDS tries to fetch it from API, the test has to fail.
- [x] Vice versa.

**Comment by themetalone** [comment]
`serverTime < data.timeStamp` shouldn't be changed since we don't want to access the server when our cached data is up to date

Could you please specify which Api you mean exactly?

**Comment by skaldo** [comment]
The logic is vice versa here: the condition is not for the HTTP request, but for the return of the LocalStorage data. Which means that the `<=` condition is correct. See: https://github.com/GSE-Project/SS2016-group2/commit/c26805105abdb804336fa356a7359d14937c3eda#diff-087aefb4c19af8b324ace2e9fd171a4bR59

Line 59 of `CitizenApplication/app/providers/data/CitizenDataService.ts`

**Comment by themetalone** [comment]
so this is fixed?

**Comment by themetalone** [comment]
I added an additional test. the other way around (fetching outdated data from the storage) is already tested
